export default function TeacherPortal({ data, notices, go }) {
  const sections = data.flatMap((item) => item.sections.map((section) => ({ ...section, className: item.name, session: item.session })))
  return <div className="teacher-portal">
    <div className="page-heading"><div><span className="eyebrow">TEACHER PORTAL</span><h1>Your teaching workspace</h1><p>Assigned classes, student lists, attendance, marks, and school communication.</p></div></div>
    <div className="stat-grid"><Stat label="Assigned classes" value={data.length} tone="blue" /><Stat label="Sections" value={sections.length} tone="mint" /><Stat label="Students" value={sections.reduce((sum, section) => sum + section.students.length, 0)} tone="gold" /><Stat label="Announcements" value={notices.length} tone="rose" /></div>
    {sections.length === 0 ? <div className="panel empty-state"><h3>No class assignments yet</h3><p>Ask an administrator to assign your teacher profile to a class section.</p></div> : <div className="teacher-class-grid">{sections.map((section) => <article className="panel teacher-class-card" key={section._id}><div className="teacher-class-heading"><div><span className="eyebrow">{section.session}</span><h2>{section.className} · Section {section.name}</h2></div><span>{section.students.length} students</span></div><div className="teacher-actions"><button className="secondary-button" onClick={() => go("attendance")}>Mark attendance</button><button className="secondary-button" onClick={() => go("results")}>Enter marks</button><button className="secondary-button" onClick={() => go("report")}>View results</button></div><div className="table-wrap"><table><thead><tr><th>Student</th><th>Admission no.</th><th>Roll no.</th><th>Father/guardian</th></tr></thead><tbody>{section.students.map((student) => <tr key={student._id}><td>{student.name}</td><td>{student.admissionNo}</td><td>{student.rollNo || "—"}</td><td>{student.fatherName || "—"}</td></tr>)}</tbody></table></div></article>)}</div>}
    <section className="portal-section"><div className="table-toolbar"><strong>Announcements and homework</strong><button className="secondary-button" onClick={() => go("notices")}>Open notices</button></div><div className="notice-list">{notices.slice(0, 4).map((notice) => <article className="panel notice-card" key={notice._id}><span className="eyebrow">{notice.category}</span><h3>{notice.title}</h3><p>{notice.body}</p></article>)}</div></section>
  </div>
}
function Stat({ label, value, tone }) { return <div className={`stat-card ${tone}`}><span>{label}</span><strong>{value}</strong><small>Assigned workspace</small></div> }
